version: "3"
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    volumes:
      - ./my-app:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: